# Generated by Django 4.1.6 on 2023-02-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0004_remove_createapplicationpagecontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='createapplicationpagecontent',
            name='repositories_other',
            field=models.BooleanField(default=True),
        ),
    ]
