# Generated by Django 4.1.6 on 2023-02-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0006_rename_repoitories_createapplicationpagecontent_repositories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createapplicationpagecontent',
            name='frameworks',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='createapplicationpagecontent',
            name='repositories',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='content',
            field=models.JSONField(),
        ),
    ]
