# Generated by Django 4.1.6 on 2023-02-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0007_alter_createapplicationpagecontent_frameworks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createapplicationpagecontent',
            name='repositories_other',
        ),
    ]
