version: '3.9'
services:
  rushiwa_django:
    build: 
      dockerfile: ./rusha_django_project/Dockerfile
    container_name: rushiwa_django
    volumes:
      - ./rusha_django_project:/code
      - ./applications:/applications
      - ./tmp:/tmp
      - ./git:/git
      - ./ansible/dev_playbook.yml:/code/dev_playbook.yml
      - ./ansible/hosts.ini:/code/hosts.ini
      - ./nginx:/nginx
    working_dir: /code
    ports:
      - 8000:8000   
    environment:
      - RUSHA_HOME=/code
    restart: always
    command: bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        ansible-playbook -i hosts.ini dev_playbook.yml &&
        python manage.py runserver 0.0.0.0:8000" 
    depends_on:
      - mssql
      - rusha_nginx

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - 1433:1433
    volumes:
      - ./mssql:/var/opt/mssql
      - ./mssql:/docker-entrypoint-initdb.d

  rusha_nginx:
    image: nginx:latest
    container_name: rusha_nginx
    ports:
      - 80:80
    expose: 
      - 80
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.conf.d:/etc/nginx/conf.d  
  rusha_ui: 
    image: node:16
    container_name: rusha_ui
    ports: 
      - 3000:3000
    volumes: 
      - ./rusha_react_app/:/src
    working_dir: /src
    
    depends_on:
      - rushiwa_django
      - mssql
      - rusha_nginx
    command: bash -c "npm install && npm start"

  

 
volumes:
  nginx:
  mssql:
  rusha_ui:
  applications:
  git:


 
      
    

    



  


    