# Generated by Django 4.1.4 on 2022-12-21 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rushiwa_applications_api', '0009_alter_application_proxy_host_name_and_or_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
