# Generated by Django 4.1.4 on 2023-01-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rushiwa_applications_api', '0010_alter_application_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NginxConfCreateQueue',
        ),
    ]
