# Generated by Django 4.1.4 on 2023-01-29 19:51

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rushiwa_applications_api', '0011_delete_nginxconfcreatequeue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
