# Generated by Django 4.1.4 on 2023-01-30 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rushiwa_applications_api', '0012_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
