# Generated by Django 4.1.4 on 2023-01-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rushiwa_applications_api', '0013_application_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rushiwa_applications_api.project'),
        ),
    ]
