# Generated by Django 4.1.4 on 2023-01-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rushiwa_applications_api', '0014_alter_application_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
