# Generated by Django 4.1.7 on 2023-03-12 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
